#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Sudoku.Android.UnitTest.Resource", IsApplication=true)]

namespace Sudoku.Android.UnitTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = Sudoku.Android.UnitTest.Resource.Id.OptionHostName;
			Xamarin.Android.NUnitLite.Resource.Id.OptionPort = Sudoku.Android.UnitTest.Resource.Id.OptionPort;
			Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = Sudoku.Android.UnitTest.Resource.Id.OptionRemoteServer;
			Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = Sudoku.Android.UnitTest.Resource.Id.OptionsButton;
			Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = Sudoku.Android.UnitTest.Resource.Id.ResultFullName;
			Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = Sudoku.Android.UnitTest.Resource.Id.ResultMessage;
			Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = Sudoku.Android.UnitTest.Resource.Id.ResultResultState;
			Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = Sudoku.Android.UnitTest.Resource.Id.ResultStackTrace;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = Sudoku.Android.UnitTest.Resource.Id.ResultsFailed;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsId = Sudoku.Android.UnitTest.Resource.Id.ResultsId;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = Sudoku.Android.UnitTest.Resource.Id.ResultsIgnored;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = Sudoku.Android.UnitTest.Resource.Id.ResultsInconclusive;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = Sudoku.Android.UnitTest.Resource.Id.ResultsMessage;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = Sudoku.Android.UnitTest.Resource.Id.ResultsPassed;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = Sudoku.Android.UnitTest.Resource.Id.ResultsResult;
			Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = Sudoku.Android.UnitTest.Resource.Id.RunTestsButton;
			Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = Sudoku.Android.UnitTest.Resource.Id.TestSuiteListView;
			Xamarin.Android.NUnitLite.Resource.Layout.options = Sudoku.Android.UnitTest.Resource.Layout.options;
			Xamarin.Android.NUnitLite.Resource.Layout.results = Sudoku.Android.UnitTest.Resource.Layout.results;
			Xamarin.Android.NUnitLite.Resource.Layout.test_result = Sudoku.Android.UnitTest.Resource.Layout.test_result;
			Xamarin.Android.NUnitLite.Resource.Layout.test_suite = Sudoku.Android.UnitTest.Resource.Layout.test_suite;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public const int OptionHostName = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int OptionPort = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int OptionRemoteServer = 2130968576;
			
			// aapt resource value: 0x7f040010
			public const int OptionsButton = 2130968592;
			
			// aapt resource value: 0x7f04000a
			public const int ResultFullName = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int ResultMessage = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int ResultResultState = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int ResultStackTrace = 2130968589;
			
			// aapt resource value: 0x7f040006
			public const int ResultsFailed = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int ResultsId = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int ResultsIgnored = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ResultsInconclusive = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int ResultsMessage = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int ResultsPassed = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int ResultsResult = 2130968580;
			
			// aapt resource value: 0x7f04000f
			public const int RunTestsButton = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int TestSuiteListView = 2130968590;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int options = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int results = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int test_result = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int test_suite = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
